version: "3.3"

# https://github.com/chefsplate/mongo-shard-docker-compose/blob/master/docker-compose.yml

volumes: # https://github.com/docker/compose/issues/2957
  mongo_shard01_vol:
  mongo_shard02_vol:

services:

  ## Config server
  mongo_configsvr:
    image: mongo
    command: mongod --port 27019 --configsvr --replSet "configserver" --bind_ip_all
    ports:
      - "27019:27019"
    deploy:
      placement:
        constraints: [node.role == manager] # put a constraint on this so it's always deployed to manager node


  ## Shards
  mongo_shard01:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet "shard01" --bind_ip_all
    ports:
      - "27018:27018"
    volumes:
      - type: volume
        source: mongo_shard01_vol
        target: /data/db
    deploy:
      placement:
        constraints: [node.hostname == ubuntunode2]

  mongo_shard02:
    image: mongo
    command: mongod --port 27020 --shardsvr --replSet "shard02" --bind_ip_all
    ports:
      - "27020:27020"
    volumes:
      - type: volume
        source: mongo_shard02_vol
        target: /data/db
    deploy:
      placement:
        constraints: [node.hostname == ubuntunode3]


  ## Router
  mongo_router:
    image: mongo
    #command: mongos --port 27017 --configdb configserver/mongodb_configsvr:27019 --bind_ip_all
    ports:
      - "27017:27017"
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - mongo_configsvr
      - mongo_shard01
      - mongo_shard02


volumes:
  mongo_shard01_vol0:
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 20
      ebstype: gp2
  mongo_shard01_vol1:
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 20
      ebstype: gp2
  mongo_shard01_vol2:
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 20
      ebstype: gp2
